const fs = require('fs');
const path = require('path');

const writeFiles = (baseDir, files) => {
    Object.keys(files).forEach(filePath => {
        const fullPath = path.join(baseDir, filePath);
        fs.mkdirSync(path.dirname(fullPath), { recursive: true });
        fs.writeFileSync(fullPath, files[filePath].trim());
    });
};

console.log("Generating Task 15 (Eureka Server)...");
writeFiles(__dirname + '/TASK-15_EurekaServer', {
    'pom.xml': `<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"><modelVersion>4.0.0</modelVersion><parent><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-parent</artifactId><version>3.2.3</version><relativePath/></parent><groupId>com.microservices</groupId><artifactId>eureka-server</artifactId><version>1.0.0</version><properties><spring-cloud.version>2023.0.0</spring-cloud.version></properties><dependencies><dependency><groupId>org.springframework.cloud</groupId><artifactId>spring-cloud-starter-netflix-eureka-server</artifactId></dependency></dependencies><dependencyManagement><dependencies><dependency><groupId>org.springframework.cloud</groupId><artifactId>spring-cloud-dependencies</artifactId><version>\${spring-cloud.version}</version><type>pom</type><scope>import</scope></dependency></dependencies></dependencyManagement></project>`,
    'src/main/resources/application.properties': `spring.application.name=eureka-server\nserver.port=8761\neureka.client.register-with-eureka=false\neureka.client.fetch-registry=false`,
    'src/main/java/com/microservices/EurekaServerApp.java': `package com.microservices;\nimport org.springframework.boot.SpringApplication;\nimport org.springframework.boot.autoconfigure.SpringBootApplication;\nimport org.springframework.cloud.netflix.eureka.server.EnableEurekaServer;\n@SpringBootApplication\n@EnableEurekaServer\npublic class EurekaServerApp {\npublic static void main(String[] args) {SpringApplication.run(EurekaServerApp.class, args);}\n}`
});

console.log("Generating Task 16 (API Gateway)...");
writeFiles(__dirname + '/TASK-16_ApiGateway', {
    'pom.xml': `<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"><modelVersion>4.0.0</modelVersion><parent><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-parent</artifactId><version>3.2.3</version><relativePath/></parent><groupId>com.microservices</groupId><artifactId>api-gateway</artifactId><version>1.0.0</version><properties><spring-cloud.version>2023.0.0</spring-cloud.version></properties><dependencies><dependency><groupId>org.springframework.cloud</groupId><artifactId>spring-cloud-starter-gateway</artifactId></dependency><dependency><groupId>org.springframework.cloud</groupId><artifactId>spring-cloud-starter-netflix-eureka-client</artifactId></dependency></dependencies><dependencyManagement><dependencies><dependency><groupId>org.springframework.cloud</groupId><artifactId>spring-cloud-dependencies</artifactId><version>\${spring-cloud.version}</version><type>pom</type><scope>import</scope></dependency></dependencies></dependencyManagement></project>`,
    'src/main/resources/application.yml': `spring:\n  application:\n    name: api-gateway\n  cloud:\n    gateway:\n      routes:\n        - id: product-service\n          uri: lb://product-service\n          predicates:\n            - Path=/api/products/**\n        - id: order-service\n          uri: lb://order-service\n          predicates:\n            - Path=/api/orders/**\nserver:\n  port: 8080\neureka:\n  client:\n    service-url:\n      defaultZone: http://localhost:8761/eureka/`,
    'src/main/java/com/microservices/ApiGatewayApp.java': `package com.microservices;\nimport org.springframework.boot.SpringApplication;\nimport org.springframework.boot.autoconfigure.SpringBootApplication;\n@SpringBootApplication\npublic class ApiGatewayApp {\npublic static void main(String[] args) {SpringApplication.run(ApiGatewayApp.class, args);}\n}`
});

console.log("Generating Task 14, 17, 18 (Microservices)...");
writeFiles(__dirname + '/TASK-14_17_18_Microservices/ProductService', {
    'pom.xml': `<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"><modelVersion>4.0.0</modelVersion><parent><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-parent</artifactId><version>3.2.3</version><relativePath/></parent><groupId>com.microservices</groupId><artifactId>product-service</artifactId><version>1.0.0</version><properties><spring-cloud.version>2023.0.0</spring-cloud.version></properties><dependencies><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-web</artifactId></dependency><dependency><groupId>org.springframework.cloud</groupId><artifactId>spring-cloud-starter-netflix-eureka-client</artifactId></dependency></dependencies><dependencyManagement><dependencies><dependency><groupId>org.springframework.cloud</groupId><artifactId>spring-cloud-dependencies</artifactId><version>\${spring-cloud.version}</version><type>pom</type><scope>import</scope></dependency></dependencies></dependencyManagement></project>`,
    'src/main/resources/application.properties': `spring.application.name=product-service\nserver.port=8081\neureka.client.service-url.defaultZone=http://localhost:8761/eureka/`,
    'src/main/java/com/microservices/ProductApp.java': `package com.microservices;\nimport org.springframework.boot.SpringApplication;\nimport org.springframework.boot.autoconfigure.SpringBootApplication;\nimport org.springframework.web.bind.annotation.*;\n@SpringBootApplication\n@RestController\n@RequestMapping("/api/products")\npublic class ProductApp {\npublic static void main(String[] args) {SpringApplication.run(ProductApp.class, args);}\n@GetMapping("/{id}")\npublic String getProduct(@PathVariable String id) {return "ProductDetails:" + id;}\n}`
});

writeFiles(__dirname + '/TASK-14_17_18_Microservices/OrderService', {
    'pom.xml': `<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"><modelVersion>4.0.0</modelVersion><parent><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-parent</artifactId><version>3.2.3</version><relativePath/></parent><groupId>com.microservices</groupId><artifactId>order-service</artifactId><version>1.0.0</version><properties><spring-cloud.version>2023.0.0</spring-cloud.version></properties><dependencies><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-web</artifactId></dependency><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-test</artifactId><scope>test</scope></dependency><dependency><groupId>org.springframework.cloud</groupId><artifactId>spring-cloud-starter-netflix-eureka-client</artifactId></dependency></dependencies><dependencyManagement><dependencies><dependency><groupId>org.springframework.cloud</groupId><artifactId>spring-cloud-dependencies</artifactId><version>\${spring-cloud.version}</version><type>pom</type><scope>import</scope></dependency></dependencies></dependencyManagement></project>`,
    'src/main/resources/application.properties': `spring.application.name=order-service\nserver.port=8082\neureka.client.service-url.defaultZone=http://localhost:8761/eureka/`,
    'src/main/java/com/microservices/OrderApp.java': `package com.microservices;\nimport org.springframework.boot.SpringApplication;\nimport org.springframework.boot.autoconfigure.SpringBootApplication;\nimport org.springframework.context.annotation.Bean;\nimport org.springframework.web.client.RestTemplate;\nimport org.springframework.cloud.client.loadbalancer.LoadBalanced;\n@SpringBootApplication\npublic class OrderApp {\n@Bean @LoadBalanced\npublic RestTemplate restTemplate() {return new RestTemplate();}\npublic static void main(String[] args) {SpringApplication.run(OrderApp.class, args);}\n}`,
    'src/main/java/com/microservices/OrderController.java': `package com.microservices;\nimport org.springframework.beans.factory.annotation.Autowired;\nimport org.springframework.web.bind.annotation.*;\nimport org.springframework.web.client.RestTemplate;\n@RestController\n@RequestMapping("/api/orders")\npublic class OrderController {\n@Autowired private RestTemplate restTemplate;\n@GetMapping("/{id}")\npublic String getOrderWithProduct(@PathVariable String id) {\nString productInfo = restTemplate.getForObject("http://product-service/api/products/" + id, String.class);\nreturn "OrderForProduct[" + productInfo + "]";\n}\n}`,
    'src/test/java/com/microservices/OrderControllerTest.java': `package com.microservices;\nimport org.junit.jupiter.api.Test;\nimport org.springframework.beans.factory.annotation.Autowired;\nimport org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;\nimport org.springframework.boot.test.mock.mockito.MockBean;\nimport org.springframework.test.web.servlet.MockMvc;\nimport org.springframework.web.client.RestTemplate;\nimport static org.mockito.Mockito.when;\nimport static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;\nimport static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;\nimport static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;\n@WebMvcTest(OrderController.class)\npublic class OrderControllerTest {\n@Autowired private MockMvc mockMvc;\n@MockBean private RestTemplate restTemplate;\n@Test\npublic void testGetOrderWithProduct() throws Exception {\nwhen(restTemplate.getForObject("http://product-service/api/products/123", String.class)).thenReturn("ProductDetails:123");\nmockMvc.perform(get("/api/orders/123"))\n.andExpect(status().isOk())\n.andExpect(content().string("OrderForProduct[ProductDetails:123]"));\n}\n}`
});

console.log("Batch 3 Done!");
