const fs = require('fs');
const path = require('path');

const writeFiles = (baseDir, files) => {
    Object.keys(files).forEach(filePath => {
        const fullPath = path.join(baseDir, filePath);
        fs.mkdirSync(path.dirname(fullPath), { recursive: true });
        fs.writeFileSync(fullPath, files[filePath].trim());
    });
};

console.log("Generating Task 8...");
writeFiles(__dirname + '/TASK-08_SpringCoreEmployee', {
    'pom.xml': `<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"><modelVersion>4.0.0</modelVersion><groupId>com.demo</groupId><artifactId>spring-core-employee</artifactId><version>1.0-SNAPSHOT</version><properties><maven.compiler.source>17</maven.compiler.source><maven.compiler.target>17</maven.compiler.target></properties><dependencies><dependency><groupId>org.springframework</groupId><artifactId>spring-context</artifactId><version>6.1.4</version></dependency></dependencies></project>`,
    'src/main/java/com/employee/AppConfig.java': `package com.employee;\nimport org.springframework.context.annotation.ComponentScan;\nimport org.springframework.context.annotation.Configuration;\n@Configuration\n@ComponentScan(basePackages="com.employee")\npublic class AppConfig {}`,
    'src/main/java/com/employee/Employee.java': `package com.employee;\npublic class Employee {\nprivate int id;\nprivate String name;\npublic Employee(int id, String name) {this.id=id;this.name=name;}\npublic int getId() {return id;}\npublic String getName() {return name;}\n@Override\npublic String toString() {return "Employee{id="+id+", name='"+name+"'}";}\n}`,
    'src/main/java/com/employee/EmployeeRepository.java': `package com.employee;\nimport org.springframework.stereotype.Component;\nimport java.util.*;\n@Component\npublic class EmployeeRepository {\nprivate Map<Integer, Employee> storage = new HashMap<>();\npublic void save(Employee emp) {storage.put(emp.getId(), emp);}\npublic List<Employee> findAll() {return new ArrayList<>(storage.values());}\n}`,
    'src/main/java/com/employee/EmployeeService.java': `package com.employee;\nimport org.springframework.beans.factory.annotation.Autowired;\nimport org.springframework.stereotype.Component;\nimport java.util.List;\n@Component\npublic class EmployeeService {\n@Autowired\nprivate EmployeeRepository repository;\npublic void addEmployee(int id, String name) {repository.save(new Employee(id, name));}\npublic List<Employee> getAllEmployees() {return repository.findAll();}\n}`,
    'src/main/java/com/employee/Main.java': `package com.employee;\nimport org.springframework.beans.factory.BeanFactory;\nimport org.springframework.context.annotation.AnnotationConfigApplicationContext;\npublic class Main {\npublic static void main(String[] args) {\nBeanFactory factory = new AnnotationConfigApplicationContext(AppConfig.class);\nEmployeeService service = factory.getBean(EmployeeService.class);\nservice.addEmployee(1, "Alice");\nservice.addEmployee(2, "Bob");\nservice.getAllEmployees().forEach(System.out::println);\n}}`
});

console.log("Generating Task 9...");
writeFiles(__dirname + '/TASK-09_SpringMVC', {
    'pom.xml': `<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"><modelVersion>4.0.0</modelVersion><groupId>com.demo</groupId><artifactId>spring-mvc</artifactId><version>1.0-SNAPSHOT</version><packaging>war</packaging><properties><maven.compiler.source>17</maven.compiler.source><maven.compiler.target>17</maven.compiler.target><failOnMissingWebXml>false</failOnMissingWebXml></properties><dependencies><dependency><groupId>org.springframework</groupId><artifactId>spring-webmvc</artifactId><version>6.1.4</version></dependency><dependency><groupId>jakarta.servlet</groupId><artifactId>jakarta.servlet-api</artifactId><version>6.0.0</version><scope>provided</scope></dependency></dependencies><build><plugins><plugin><groupId>org.apache.tomcat.maven</groupId><artifactId>tomcat7-maven-plugin</artifactId><version>2.2</version><configuration><path>/</path></configuration></plugin></plugins></build></project>`,
    'src/main/java/com/demo/config/AppConfig.java': `package com.demo.config;\nimport org.springframework.context.annotation.ComponentScan;\nimport org.springframework.context.annotation.Configuration;\nimport org.springframework.web.servlet.config.annotation.EnableWebMvc;\n@Configuration\n@EnableWebMvc\n@ComponentScan(basePackages = "com.demo.controller")\npublic class AppConfig {}`,
    'src/main/java/com/demo/config/WebAppInitializer.java': `package com.demo.config;\nimport org.springframework.web.servlet.support.AbstractAnnotationConfigDispatcherServletInitializer;\npublic class WebAppInitializer extends AbstractAnnotationConfigDispatcherServletInitializer {\n@Override\nprotected Class<?>[] getRootConfigClasses() {return null;}\n@Override\nprotected Class<?>[] getServletConfigClasses() {return new Class<?>[]{AppConfig.class};}\n@Override\nprotected String[] getServletMappings() {return new String[]{"/"};}\n}`,
    'src/main/java/com/demo/controller/EmployeeController.java': `package com.demo.controller;\nimport org.springframework.stereotype.Controller;\nimport org.springframework.web.bind.annotation.GetMapping;\nimport org.springframework.web.bind.annotation.ResponseBody;\n@Controller\npublic class EmployeeController {\n@GetMapping("/details")\n@ResponseBody\npublic String getEmployeeDetails() {return "<h3>Employee Details Flow (No XML)</h3><p>Name: John Smith<br/>Id: 101<br/>Dept: IT</p>";}\n}`
});

console.log("Generating Task 10...");
writeFiles(__dirname + '/TASK-10_SpringBootCRUD', {
    'pom.xml': `<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"><modelVersion>4.0.0</modelVersion><parent><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-parent</artifactId><version>3.2.3</version><relativePath/></parent><groupId>com.demo</groupId><artifactId>student-crud</artifactId><version>1.0-SNAPSHOT</version><dependencies><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-data-jpa</artifactId></dependency><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-web</artifactId></dependency><dependency><groupId>com.h2database</groupId><artifactId>h2</artifactId><scope>runtime</scope></dependency></dependencies><build><plugins><plugin><groupId>org.springframework.boot</groupId><artifactId>spring-boot-maven-plugin</artifactId></plugin></plugins></build></project>`,
    'src/main/resources/application.properties': `spring.application.name=student-crud\nspring.datasource.url=jdbc:h2:mem:testdb\nspring.datasource.driverClassName=org.h2.Driver\nspring.datasource.username=sa\nspring.datasource.password=\nspring.jpa.database-platform=org.hibernate.dialect.H2Dialect\nspring.h2.console.enabled=true`,
    'src/main/java/com/demo/StudentCrudApplication.java': `package com.demo;\nimport org.springframework.boot.SpringApplication;\nimport org.springframework.boot.autoconfigure.SpringBootApplication;\n@SpringBootApplication\npublic class StudentCrudApplication {\npublic static void main(String[] args) {SpringApplication.run(StudentCrudApplication.class, args);}\n}`,
    'src/main/java/com/demo/Student.java': `package com.demo;\nimport jakarta.persistence.Entity;\nimport jakarta.persistence.Id;\nimport jakarta.persistence.Table;\nimport jakarta.persistence.Column;\n@Entity\n@Table(name="students")\npublic class Student {\n@Id @Column(name="student_id")\nprivate Long id;\n@Column(name="student_name")\nprivate String name;\npublic Long getId() {return id;}\npublic void setId(Long id) {this.id=id;}\npublic String getName() {return name;}\npublic void setName(String name) {this.name=name;}\n}`,
    'src/main/java/com/demo/StudentRepository.java': `package com.demo;\nimport org.springframework.data.repository.CrudRepository;\npublic interface StudentRepository extends CrudRepository<Student, Long> {}`
});

console.log("Generating Task 11...");
writeFiles(__dirname + '/TASK-11_SpringDataJPA', {
    'pom.xml': `<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"><modelVersion>4.0.0</modelVersion><parent><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-parent</artifactId><version>3.2.3</version><relativePath/></parent><groupId>com.demo</groupId><artifactId>spring-data-jpa</artifactId><version>1.0-SNAPSHOT</version><dependencies><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-data-jpa</artifactId></dependency><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-web</artifactId></dependency><dependency><groupId>com.h2database</groupId><artifactId>h2</artifactId><scope>runtime</scope></dependency></dependencies><build><plugins><plugin><groupId>org.springframework.boot</groupId><artifactId>spring-boot-maven-plugin</artifactId></plugin></plugins></build></project>`,
    'src/main/resources/application.properties': `spring.application.name=spring-data-jpa\nspring.datasource.url=jdbc:h2:mem:jpa_db\nspring.h2.console.enabled=true`,
    'src/main/java/com/demo/Application.java': `package com.demo;\nimport org.springframework.boot.SpringApplication;\nimport org.springframework.boot.autoconfigure.SpringBootApplication;\n@SpringBootApplication\npublic class Application {\npublic static void main(String[] args) {SpringApplication.run(Application.class, args);}\n}`,
    'src/main/java/com/demo/Student.java': `package com.demo;\nimport jakarta.persistence.Entity;\nimport jakarta.persistence.Id;\nimport jakarta.persistence.GeneratedValue;\nimport jakarta.persistence.GenerationType;\n@Entity\npublic class Student {\n@Id @GeneratedValue(strategy = GenerationType.IDENTITY) private Long id;\nprivate String name;\nprivate String department;\nprivate int age;\npublic Student() {}\npublic Student(String n, String d, int a) {name=n;department=d;age=a;}\npublic Long getId() {return id;}\npublic String getName() {return name;}\npublic String getDepartment() {return department;}\npublic int getAge() {return age;}\n}`,
    'src/main/java/com/demo/StudentRepository.java': `package com.demo;\nimport org.springframework.data.jpa.repository.JpaRepository;\nimport java.util.List;\nimport org.springframework.data.domain.Pageable;\npublic interface StudentRepository extends JpaRepository<Student, Long> {\nList<Student> findByDepartment(String department);\nList<Student> findByAgeGreaterThan(int age, Pageable pageable);\n}`,
    'src/main/java/com/demo/Runner.java': `package com.demo;\nimport org.springframework.boot.CommandLineRunner;\nimport org.springframework.stereotype.Component;\nimport org.springframework.data.domain.PageRequest;\n@Component\npublic class Runner implements CommandLineRunner {\nprivate final StudentRepository repo;\npublic Runner(StudentRepository r) {repo=r;}\n@Override\npublic void run(String... args) throws Exception {\nrepo.save(new Student("Alice", "CS", 20));\nrepo.save(new Student("Bob", "IT", 22));\nrepo.save(new Student("Charlie", "CS", 23));\nSystem.out.println("CS Students:");\nrepo.findByDepartment("CS").forEach(s -> System.out.println(s.getName()));\nSystem.out.println("Students older than 21 (Paginated limit 1):");\nrepo.findByAgeGreaterThan(21, PageRequest.of(0, 1)).forEach(s -> System.out.println(s.getName()));\n}\n}`
});

console.log("Generating Task 12 & 13...");
writeFiles(__dirname + '/TASK-12_13_SpringBootREST_ExceptionHandling', {
    'pom.xml': `<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"><modelVersion>4.0.0</modelVersion><parent><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-parent</artifactId><version>3.2.3</version><relativePath/></parent><groupId>com.demo</groupId><artifactId>rest-api</artifactId><version>1.0-SNAPSHOT</version><dependencies><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-web</artifactId></dependency><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-validation</artifactId></dependency></dependencies></project>`,
    'src/main/java/com/demo/ApiApplication.java': `package com.demo;\nimport org.springframework.boot.SpringApplication;\nimport org.springframework.boot.autoconfigure.SpringBootApplication;\n@SpringBootApplication\npublic class ApiApplication {\npublic static void main(String[] args) {SpringApplication.run(ApiApplication.class, args);}\n}`,
    'src/main/java/com/demo/Product.java': `package com.demo;\nimport jakarta.validation.constraints.NotBlank;\nimport jakarta.validation.constraints.Positive;\npublic class Product {\nprivate Long id;\n@NotBlank(message = "Name is mandatory")\nprivate String name;\n@Positive(message = "Price must be greater than zero")\nprivate double price;\npublic Product(Long i, String n, double p) {id=i;name=n;price=p;}\npublic Long getId() {return id;}\npublic String getName() {return name;}\npublic double getPrice() {return price;}\npublic void setId(Long i) {id=i;}\npublic void setName(String n) {name=n;}\npublic void setPrice(double p) {price=p;}\n}`,
    'src/main/java/com/demo/ProductController.java': `package com.demo;\nimport org.springframework.web.bind.annotation.*;\nimport jakarta.validation.Valid;\nimport java.util.*;\n@RestController\n@RequestMapping("/api/products")\npublic class ProductController {\nprivate List<Product> products = new ArrayList<>();\n@GetMapping\npublic List<Product> getAll() {return products;}\n@PostMapping\npublic Product create(@Valid @RequestBody Product p) {p.setId((long)(products.size()+1)); products.add(p); return p;}\n@GetMapping("/{id}")\npublic Product getById(@PathVariable Long id) {\nreturn products.stream().filter(p -> p.getId().equals(id)).findFirst().orElseThrow(() -> new RuntimeException("Product not found"));\n}\n}`,
    'src/main/java/com/demo/GlobalExceptionHandler.java': `package com.demo;\nimport org.springframework.http.HttpStatus;\nimport org.springframework.http.ResponseEntity;\nimport org.springframework.web.bind.MethodArgumentNotValidException;\nimport org.springframework.web.bind.annotation.ControllerAdvice;\nimport org.springframework.web.bind.annotation.ExceptionHandler;\nimport java.util.HashMap;\nimport java.util.Map;\n@ControllerAdvice\npublic class GlobalExceptionHandler {\n@ExceptionHandler(MethodArgumentNotValidException.class)\npublic ResponseEntity<Map<String, String>> handleValidation(MethodArgumentNotValidException ex) {\nMap<String, String> errors = new HashMap<>();\nex.getBindingResult().getFieldErrors().forEach(error -> errors.put(error.getField(), error.getDefaultMessage()));\nreturn ResponseEntity.status(HttpStatus.BAD_REQUEST).body(errors);\n}\n@ExceptionHandler(RuntimeException.class)\npublic ResponseEntity<String> handleRuntime(RuntimeException ex) {\nreturn ResponseEntity.status(HttpStatus.NOT_FOUND).body(ex.getMessage());\n}\n}`
});

console.log("Batch 2 Done!");
